### ISSUE TITLE
magic/identify.py:62: RuntimeWarning: Implicitly cleaning up <magic.api.LP_Cookie object at 0x10558c0>

### ISSUE THREAD

**Issue by ssbarnea** [aliles/filemagic#9] opened 2013-12-18 09:30 UTC
On Ubuntu I get the following runtime Warning which is very annoying for a script that is used to run in crontab.

/usr/local/lib/python2.7/dist-packages/magic/identify.py:62: RuntimeWarning: Implicitly cleaning up <magic.api.LP_Cookie object at 0x10558c0>
  CleanupWarning)

python 2.7.5+
magic 1.6

**Comment by aliles** [comment] 2013-12-18 09:50
Thank you for opening this issue; this is most likely caused by failing to correctly close the Magic object before the script exits. The intention of this behaviour is to warn the user that the program is relying on deterministic garbage collection (as used by CPython) which is not used by other python implementations such as PyPy or Jython. CPython has similar behaviour for file objects.

This issue indicates problems with both the exception message (to obscure to interpret) and with the filemagic documentation.

Are you able to share a small code snippet of the script with me so that I may confirm the cause of the warning and suggest a fix?

**Comment by ssbarnea** [comment] 2013-12-18 10:09
Sure, let me give you the link https://bitbucket.org/bspeakmon/jira-python/src/96e07cc4e3c1c9c3454fb957bc4da6900ebbdb32/jira/client.py?at=master#cl-1523

**Comment by aliles** [comment] 2013-12-18 11:39
I've submitted a pull request to the jira-python project that should prevent the resource warning being generated (https://bitbucket.org/bspeakmon/jira-python/pull-request/35/fix-warning-for-implicit-close-of-libmagic/diff). This based on using Python's weakref module to ensure that when the JIRA instance is garbage collected the Magic object is closed. I've put a simplified example of this code in a gist, https://gist.github.com/aliles/8020898.

This doesn't really address the root cause of the issue, which is documentation. If you have any suggestions on how to refactor the 'Memory Management' section of the documentation (http://filemagic.readthedocs.org/en/latest/guide.html#memory-management) I would be grateful to hear them. I will also look to rephrase the exception message to be more explanatory as to what the warning being reported means.

**Comment by aliles** [comment] 2014-02-04 11:16
The resource warning has been rephrased in 616dfdf5b381907a9ee0d905ba03680f09016687. It is now more descriptive of why the warning was raised and how to avoid it:

```
magic.Magic() not closed before being garbage collected. Magic.close() should be called when finished with
```

This change will be included in the next filemagicrelease.

**Closed as completed by aliles** 2014-02-04 11:16 UTC

**Comment by ssbarnea** [comment] 2015-09-02 12:31
Can we get this fixed? I think that asking for a close call is against python principles. 

It seems that your workaround implementation doesn't really work as expected.

```
Exception TypeError: 'cleanup() takes no arguments (1 given)' in <function cleanup at 0x10b48a938> ignored
/Users/sorins/Library/Python/2.7/lib/python/site-packages/magic/identify.py:62: RuntimeWarning: Implicitly cleaning up <magic.api.LP_Cookie object at 0x10b26c830>
  CleanupWarning)
Exception TypeError: 'cleanup() takes no arguments (1 given)' in <function cleanup at 0x10b483b18> ignored
/Users/sorins/Library/Python/2.7/lib/python/site-packages/magic/identify.py:62: RuntimeWarning: Implicitly cleaning up <magic.api.LP_Cookie object at 0x10b26c4d0>
  CleanupWarning)
```
